import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/src/app/globals.css";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/src/auth";
import { Toaster } from "@/src/components/ui/sonner";
import { ThemeProvider } from "@/src/components/theme-provider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
    <html lang="en">
      <body>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <Toaster/>
        {children}
        </ThemeProvider>
        </body>
    </html>
    </SessionProvider>
  );
}
