import React from 'react';
import { BellIcon, MoonIcon, SunIcon ,BoxIcon, HomeIcon, PersonIcon, BarChartIcon, DropdownMenuIcon} from '@radix-ui/react-icons';
// import { SideBar } from '@/src/components/dashboard/side-bar';
import Link from 'next/link';
import { Button } from '@/src/components/ui/button';
import { FaSearch, FaShoppingBasket, FaShoppingCart, FaUserCircle } from 'react-icons/fa';
import { Badge } from '@/src/components/ui/badge';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/src/components/ui/card';
import { Input } from '@/src/components/ui/input';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger } from '@/src/components/ui/dropdown-menu';
import { Sheet, SheetContent, SheetTrigger } from '@/src/components/ui/sheet';
import DashboardNavBar from '@/src/components/dashboard/nav-bar';
import Sidebar from '@/src/components/dashboard/side-bar';
import { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};


export default async function DashboardLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {

  

  return (
    <body>
    <div className="h-screen w-screen bg-white dark:bg-slate-900">
    <div className="grid min-h-screen w-full md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr]">
        <Sidebar/>
      <div className="flex flex-col">
        <DashboardNavBar/>
        <main className="flex flex-1 flex-col gap-4 p-4 lg:gap-6 lg:p-6">
        {children}
        </main>
      </div>
    </div>
    </div>
    </body>
  );
};


